resources:
- name: source
  type: git
  source:
    uri: https://github.com/subnova/docker-registry-artifact-plugin

jobs:
- name: build
  plan:
  - get: source
    trigger: true
  - task: build
    file: source/concourse/tasks/build.yaml

